language: c
compiler: gcc
os: linux
dist: xenial

addons:
  apt:
    packages: &default_packages
      - libbsd-dev

matrix:
  #fast_finish: True
  include:
    - stage: Tests
      name: Code checking
      addons:
        apt:
          packages:
            - shellcheck
      script:
        - shellcheck build.sh

script:
  - ./build.sh

notifications:
  email: false