language: c
compiler: gcc
os: linux
dist: xenial

matrix:
  #fast_finish: True
  include:
    #- name: Hardening Checks
    #  addons:
    #    apt:
    #      packages: &default_packages
    #        - libbsd-dev
    #        - devscripts
    #        - hardening-includes
    #  before_install:
    #    - wget https://github.com/slimm609/checksec.sh/archive/master.zip && unzip -q master.zip
    #  script:
    #    - ./build.sh Debug
    #    - ./checksec.sh-master/checksec -f Debug/secure_socket && ./checksec.sh-master/checksec -ff Debug/secure_socket
    #    - hardening-check -c -v Debug/secure_socket

    - name: Quality Checks
      git:
        depth: false # Sonar doesn't like shallow clones
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: &default_packages
            - libbsd-dev
            - gcc-7
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      env:
        - MATRIX_EVAL="CC=gcc-7"
      script:
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - shellcheck -x build.sh
        - build-wrapper-linux-x86-64 --out-dir bw-output ./build.sh Coverage && ls -al bw-output/
        - ./run.sh & python3 src/client_test.py

      after_success:
        - chmod +x coverage.sh && ./coverage.sh && sonar-scanner
        - bash <(curl -s https://codecov.io/bash) -s gcov/

notifications:
  email: false