language: c
compiler: gcc
os: linux
dist: xenial

matrix:
  #fast_finish: True
  include:
    - name: Hardening Checks
      addons:
        apt:
          packages: &default_packages
            - libbsd-dev
            - devscripts
            - hardening-includes
      before_install:
        - wget https://github.com/slimm609/checksec.sh/archive/master.zip && unzip -q master.zip
      script:
        - ./build.sh Debug
        - ./checksec.sh-master/checksec -f Debug/secure_socket && ./checksec.sh-master/checksec -ff Debug/secure_socket
        - hardening-check -c -v Debug/secure_socket

    - name: Sonar checking
      addons:
        apt:
          packages: &default_packages
            - libbsd-dev
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - shellcheck -x build.sh
        #- ./build.sh Coverage
        - cd Coverage
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
        - sonar-scanner


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false