language: c
compiler: gcc
os: linux
dist: xenial

matrix:
  #fast_finish: True
  include:
    #- name: Hardening Checks
    #  addons:
    #    apt:
    #      packages: &default_packages
    #        - libbsd-dev
    #        - devscripts
    #        - hardening-includes
    #  before_install:
    #    - wget https://github.com/slimm609/checksec.sh/archive/master.zip && unzip -q master.zip
    #  script:
    #    - ./build.sh Debug
    #    - ./checksec.sh-master/checksec -f Debug/secure_socket && ./checksec.sh-master/checksec -ff Debug/secure_socket
    #    - hardening-check -c -v Debug/secure_socket

    - name: Quality Checks
      git:
        depth: false # Sonar doesn't like shallow clones
      addons:
        apt:
          packages: &default_packages
            - libbsd-dev
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - shellcheck -x build.sh
        - build-wrapper-linux-x86-64 --out-dir bw-output ./build.sh Coverage && ls -al bw-output/
        - ./run.sh
        - sonar-scanner
      after_success:
        - bash <(curl -s https://codecov.io/bash) -s Coverage/CMakeFiles/secure_socket.dir/src/

notifications:
  email: false