language: c
compiler: gcc
os: linux
dist: xenial


before_install:
  - sudo add-apt-repository -y ppa:jonathonf/gcc-6.3
  - sudo apt-get update
  - VER=6.3.0-21ubuntu1~16.04.york0
  - sudo apt-get -y install gcc-6-base=$VER gcc-6=$VER g++-6=$VER cpp-6=$VER libgcc-6-dev=$VER libstdc++-6-dev=$VER libasan3=$VER
  - sudo apt-get -y install libbsd-dev

script:
  - ./build.sh && ./run.sh